window.AL_IHSAN_STATIC_DATA = {
  campaigns: [
    {
      id: "build-10-masjids",
      title: "Build 10 village masjids",
      cause: "Masjid construction",
      icon: "landmark",
      unitName: "masjid",
      unitCost: 20000,
      quantity: 10,
      target: 200000,
      raised: 0,
      currency: "USD",
      status: "active",
      description: "A long-term sadaqah jariyah campaign to build ten complete village masjids in Uganda.",
      location: "Jinja, Uganda",
      beneficiaries: "Village worshippers",
      milestone: "Campaign open",
      nextNeed: "First masjid funding",
      priceNote: "$20,000 funds one complete village masjid, from planning and materials to worship-ready completion.",
      priceUpdatedAt: "2026-05-11T11:13:43.293Z",
    },
    {
      id: "water-wells-uganda",
      title: "Clean water wells",
      cause: "Water well construction",
      icon: "droplets",
      unitName: "well",
      unitCost: 1100,
      quantity: 10,
      target: 11000,
      raised: 0,
      currency: "USD",
      status: "active",
      description: "Fund deep community water wells for rural families, children, and elders.",
      location: "Rural Uganda",
      beneficiaries: "Families and children",
      milestone: "Campaign open",
      nextNeed: "First well funding",
      priceNote: "$1,100 is the current water well estimate.",
      priceUpdatedAt: "2026-05-11T11:13:43.293Z",
    },
    {
      id: "quran-copies",
      title: "Quran distribution",
      cause: "Quran distribution",
      icon: "book-open",
      unitName: "Quran",
      unitCost: 10,
      quantity: 100,
      target: 1000,
      raised: 30,
      currency: "USD",
      status: "active",
      description: "Give Quran copies to children, elders, new Muslims, and students of knowledge.",
      location: "Uganda",
      beneficiaries: "Students of knowledge",
      milestone: "Distribution active",
      nextNeed: "More Quran copies",
      priceNote: "$10 is the current Quran copy estimate.",
      priceUpdatedAt: "2026-05-11T11:13:43.293Z",
    },
  ],
  reports: [],
  fieldMap: {
    headquarters: {
      title: "Jinja City headquarters",
      location: "Jinja City, Uganda",
    },
    sites: [
      {
        title: "Build 10 village masjids",
        type: "campaign",
        location: "Jinja, Uganda",
        metric: "Campaign open",
      },
      {
        title: "Clean water wells",
        type: "campaign",
        location: "Rural Uganda",
        metric: "Campaign open",
      },
      {
        title: "Quran distribution",
        type: "campaign",
        location: "Uganda",
        metric: "Distribution active",
      },
    ],
  },
  media: [
    {
      id: "3195e497-02a4-4f22-9fe6-35507ae5561c",
      kind: "image",
      src: "uploads/3195e497-02a4-4f22-9fe6-35507ae5561c.png",
      title: "Donate a Qurban",
      caption: "Support qurban giving for families in need.",
      alt: "Qurban donation campaign poster",
    },
  ],
};
